name: Build and Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.16.0'

    - name: Change to frontend directory
      run: cd clinica-frontend

    - name: Install dependencies
      run: npm install
      working-directory: ./clinica-frontend

    - name: Build
      run: CI=false npm run build
      working-directory: ./clinica-frontend

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./clinica-frontend/build
